app:
  name: "log system"
  port: 8080

database:
  user: "root"
  passowrd: "12345678"
  host: "127.0.0.1"
  port: 3306
  dbname: gorm

log:                        #zap日志框架配置
  level: debug              # 日志级别：debug, info, warn, error, dpanic, panic, fatal
  format: console           # 输出格式：json 或 console
  output: stdout&file       # 输出位置：stdout, stderr, stdout&file, file
  logfilepath: "./logfiles/"
  encoding:
    time_key: time          # 时间字段的 key
    level_key: level        # 日志级别字段的 key
    caller_key: caller      # 调用位置字段的 key
    message_key: msg        # 日志消息字段的 key
    stacktrace_key: stack   # 堆栈字段的 key
    time_format: iso8601    # 时间格式：iso8601(常见的 2025-09-24T15:04:05+08:00 格式)| epoch(时间戳（秒/毫秒）), 或自定义格式|custom 自定义
    time_format_custom: "2006-01-02 15:04:05" #带时区 "2006-01-02T15:04:05Z07:00" ｜ "2006/01/02"
  options:
    add_caller: true        # 是否打印调用者（文件名:行号）
    development: false      # 是否开启开发模式（影响日志输出的额外信息）
